### ISSUE TITLE
HomuraShakuishi/unity_study#9チェック事項

### ISSUE THREAD

**Issue by murnana** [murnana/unity_study_with_RyuTatsu#10]
HomuraShakuishi/unity_study#9 より

- [ ] 敵が死んでから、時間経過で次の敵が出現するのか
- [ ] 回復アイテムをとった瞬間、回復するのか
- [ ] 最大体力を超えて回復しないのか
- [ ] 無敵アイテムによって、プレイヤーが一定時間無敵になるのか

**Comment by murnana** [comment]
次回チェック項目
- [ ] murnana/unity_study_with_RyuTatsu#11 .gitignoreの位置・2
- [ ] murnana/unity_study_with_RyuTatsu#12 プロジェクトが重い
- [ ] murnana/unity_study_with_RyuTatsu#1 プロジェクト追加方法

**Comment by HomuraShakuishi** [comment]
.gitignore移動完了、sky~ファイルごと移動　最後のはよく分からんからパス

**Comment by murnana** [comment]
追加事項: 
- [ ] アイテムドロップシステム

**Comment by HomuraShakuishi** [comment]
スクリプトが追加されていなかったので、追加しました。すべてあるはずなので、おそらく動くと思います
